export const widgets = [
  {
    id: 1,
    name: "Widget A",
    category: "electronics",
    price: 50,
    description: "A high-quality electronic gadget for tech enthusiasts.",
    image: "widget-a.jpg",
  },
  {
    id: 2,
    name: "Widget B",
    category: "clothing",
    price: 20,
    description: "Stylish and comfortable clothing for all seasons.",
    image: "widget-b.jpg",
  },
  {
    id: 3,
    name: "Widget C",
    category: "electronics",
    price: 30,
    description: "A versatile gadget for daily tech needs.",
    image: "widget-c.jpg",
  },
  {
    id: 4,
    name: "Widget D",
    category: "home",
    price: 40,
    description: "A home decoration item that adds style to any room.",
    image: "widget-d.jpg",
  },
  {
    id: 5,
    name: "Widget E",
    category: "clothing",
    price: 10,
    description: "Comfortable and breathable clothing for all-day wear.",
    image: "widget-e.jpg",
  },
  {
    id: 6,
    name: "Widget F",
    category: "electronics",
    price: 100,
    description: "A high-end electronic gadget for professionals.",
    image: "widget-f.jpg",
  },
  {
    id: 7,
    name: "Widget G",
    category: "home",
    price: 70,
    description: "A home appliance to make your life easier.",
    image: "widget-g.jpg",
  },
  {
    id: 8,
    name: "Widget H",
    category: "clothing",
    price: 35,
    description: "Trendy clothing that is perfect for casual wear.",
    image: "widget-h.jpg",
  },
  {
    id: 9,
    name: "Widget I",
    category: "home",
    price: 80,
    description: "The ultimate smart home accessory for convenience.",
    image: "widget-i.jpg",
  },
];
